project:
  type: website
  output-dir: docs
  
website:
  title: "Alexander Lloyd Lemna"
  description: "Personal website and blog"
  site-url: "https://alexlemna.github.io"
  navbar:
    left:
      - href: index.md
        text: home
      - href: notes.md
        text: notes
      - text: projects
        menu:
          - href: projects/keydrop.md
            text: Keydrop
      - href: blog.md
        text: blog
    right:
      - text: about
        menu:
          - href: about.md
            text: me
          - href: this_site.md
            text: this site
  page-footer:
    left: "© 2025 Alexander Lloyd Lemna"
    # right: "Built with [Quarto](https://quarto.org)"
  
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - solar
    css: styles.css
    toc: true



