project:
  type: website
  output-dir: ./docs

  # # Path rewrites for clean URLs
  # render:
  #   - "/source/*.md"

website:
  title: "Alexander Lloyd Lemna"
  description: "Personal website and blog"
  site-url: "https://alexlemna.github.io"
  repo-url: "https://github.com/AlexLemna/alexlemna.github.io"
  repo-subdir: /docs

  bread-crumbs: true

  # Custom URL path mappings
  sidebar:
    - title: "Notes"
      contents:
        - section: "Explanations"
          contents: # "notes/explanations/*.md"
            - href: notes/explanations/SSH-Overview.md
            - href: notes/explanations/SSH-Guide-to-Keys.md
          href: "notes/explanations/"
        - section: "Tutorials"
          contents: "notes/tutorials/*.md"
          href: "notes/tutorials/"
        - section: "How-to Guides"
          contents: "notes/how-to/*.md"
          href: "notes/how-to-guides/"
        - section: "References"
          contents: "notes/references/*.md"
          href: "notes/references/"

  navbar:
    left:
      - text: home
        href: index.md
      - text: notes
        menu:
          - text: notes index
            href: notes/index.md
          - text: explanations
            href: notes/explanations/index.md
          - text: tutorials
            href: notes/tutorials/index.md
          - text: how-to guides
            href: notes/how-to/index.md
          - text: references & resources
            href: notes/references/index.md
      - text: projects
        menu:
          - text: keydrop
            href: projects/keydrop.md
    right:
      - text: about
        menu:
          - text: about me
            href: about.md
          - text: about this site
            href: this_site.md
      - text: reuse
        href: reuse.md
      - icon: rss
        href: feed.xml

  page-footer:
    left: "© 2025 Alexander Lloyd Lemna"
    # right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - solar
    css: styles.css
    toc: true
