project:
  type: website
  output-dir: docs

website:
  title: "Alexander Lloyd Lemna"
  description: "Personal website and blog"
  site-url: "https://alexlemna.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Blog
        menu:
          - href: posts/first-post.md
            text: First Post
          - href: posts/second-post.md
            text: Second Post
  page-footer:
    left: "© 2025 Alexander Lloyd Lemna"
    right: "Built with [Quarto](https://quarto.org)"
  
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - solar
    css: styles.css
    toc: true



